language: scala

scala:
  - 2.12.7

script:
  - sbt clean coverage test coverageReport coverageAggregate

after_success:
  - sbt coverageReport coverageAggregate coveralls

notifications:
  email: false
